#!/usr/bin/env python3
"""
Скрипт для автоматичного перекладу nodeDefs.json на українську мову.
Використовує словник технічних термінів ComfyUI та паттерни перекладу.
"""
import json
import re
import os

# Словник перекладів для поширених термінів та паттернів
TERM_TRANSLATIONS = {
    # Дії
    "Load": "Завантажити",
    "Save": "Зберегти",
    "Preview": "Попередній перегляд",
    "Encode": "Кодувати",
    "Decode": "Декодувати",
    "Apply": "Застосувати",
    "Create": "Створити",
    "Generate": "Генерувати",
    "Convert": "Конвертувати",
    "Transform": "Трансформувати",
    "Resize": "Змінити розмір",
    "Crop": "Обрізати",
    "Rotate": "Повернути",
    "Flip": "Відзеркалити",
    "Mirror": "Дзеркало",
    "Blur": "Розмити",
    "Sharpen": "Зостришити",
    "Noise": "Шум",
    "Mask": "Маска",
    "Merge": "Об'єднати",
    "Split": "Розділити",
    "Batch": "Партія",
    "Repeat": "Повторити",
    "Loop": "Цикл",
    "Schedule": "Розклад",
    "Sampler": "Семплер",
    "Sampling": "Семплування",
    "Guide": "Напрям",
    "Condition": "Кондиція",
    "Conditioning": "Кондиціювання",
    "Prompt": "Промпт",
    "Text": "Текст",
    "Image": "Зображення",
    "Video": "Відео",
    "Audio": "Аудіо",
    "Model": "Модель",
    "Latent": "Латент",
    "VAE": "VAE",
    "CLIP": "CLIP",
    "ControlNet": "ControlNet",
    "GLIGEN": "GLIGEN",
    "LoRA": "LoRA",
    "Style": "Стиль",
    "Color": "Колір",
    "Brightness": "Яскравість",
    "Contrast": "Контраст",
    "Hue": "Відтінок",
    "Saturation": "Насиченість",
    "Gamma": "Гама",
    "Exposure": "Експозиція",
    "Shadow": "Тінь",
    "Highlight": "Світлина",
    "Depth": "Глибина",
    "Normal": "Нормаль",
    "Edge": "Край",
    "Pose": "Поза",
    "Segmentation": "Сегментація",
    "Detection": "Виявлення",
    "Tracking": "Відстеження",
    "Flow": "Потік",
    "Histogram": "Гістограма",
    "Curve": "Крива",
    "Gradient": "Градієнт",
    "Grid": "Сітка",
    "Tile": "Плитка",
    "Stamp": "Штамп",
    "Watermark": "Водяний знак",
    "Inpaint": "Інпейнтинг",
    "Outpaint": "Аутпейнтинг",
    "Fill": "Заповнення",
    "Remove": "Видалити",
    "Background": "Фон",
    "Foreground": "Передній план",
    "Alpha": "Альфа",
    "Channel": "Канал",
    "Layer": "Шар",
    "Stack": "Стек",
    "Concatenate": "Конкатенація",
    "Interleave": "Чергування",
    "Shuffle": "Перемішати",
    "Sort": "Сортувати",
    "Filter": "Фільтр",
    "Threshold": "Поріг",
    "Quantize": "Квантизувати",
    "Dequantize": "Деквантизувати",
    "Compress": "Стиснути",
    "Decompress": "Розпакувати",
    "Encrypt": "Шифрувати",
    "Decrypt": "Розшифрувати",
    "Hash": "Хеш",
    "Sign": "Підпис",
    "Verify": "Перевірити",
    "Validate": "Валідувати",
    "Test": "Тест",
    "Debug": "Налагодження",
    "Info": "Інформація",
    "Status": "Статус",
    "Progress": "Прогрес",
    "History": "Історія",
    "Cache": "Кеш",
    "Buffer": "Буфер",
    "Queue": "Черга",
    "Pause": "Пауза",
    "Resume": "Відновити",
    "Stop": "Зупинити",
    "Start": "Почати",
    "Reset": "Скинути",
    "Clear": "Очистити",
    "Set": "Встановити",
    "Get": "Отримати",
    "Read": "Прочитати",
    "Write": "Записати",
    "Open": "Відкрити",
    "Close": "Закрити",
    "Show": "Показати",
    "Hide": "Приховати",
    "Enable": "Увімкнути",
    "Disable": "Вимкнути",
    "Toggle": "Перемкнути",
    "Switch": "Перемкнути",
    "Select": "Вибрати",
    "Deselect": "Скасувати вибір",
    "Pick": "Вибрати",
    "Choose": "Обрати",
    "Browse": "Оглянути",
    "Search": "Пошук",
    "Find": "Знайти",
    "Replace": "Замінити",
    "Edit": "Редагувати",
    "Copy": "Копіювати",
    "Paste": "Вставити",
    "Cut": "Вирізати",
    "Duplicate": "Дублювати",
    "Clone": "Клонувати",
    "Move": "Рухати",
    "Align": "Вирівняти",
    "Center": "Центр",
    "Fit": "Підлаштувати",
    "Expand": "Розгорнути",
    "Collapse": "Згорнути",
    "Fold": "Скласти",
    "Unfold": "Розгорнути",
    "Import": "Імпорт",
    "Export": "Експорт",
    "Upload": "Завантажити",
    "Download": "Завантажити",
    "Sync": "Синхронізувати",
    "Update": "Оновити",
    "Refresh": "Оновити",
    "Reload": "Перезавантажити",
    "Restart": "Перезапустити",
    "Reboot": "Перезавантажити",
    "Install": "Встановити",
    "Uninstall": "Видалити",
    "Configure": "Налаштувати",
    "Setup": "Налаштування",
    "Init": "Ініціалізувати",
    "Initialize": "Ініціалізувати",
    "Build": "Збудувати",
    "Compile": "Компілювати",
    "Run": "Запустити",
    "Execute": "Виконати",
    "Process": "Обробити",
    "Handle": "Обробити",
    "Manage": "Керувати",
    "Control": "Керувати",
    "Monitor": "Моніторинг",
    "Track": "Відстежувати",
    "Log": "Лог",
    "Record": "Записати",
    "Capture": "Захопити",
    "Extract": "Виділити",
    "Insert": "Вставити",
    "Add": "Додати",
    "Remove": "Видалити",
    "Delete": "Видалити",
    "Create": "Створити",
    "Destroy": "Знищити",
    "Make": "Створити",
    "Build": "Збудувати",
    "Construct": "Створити",
    "Form": "Форма",
    "Shape": "Форма",
    "Size": "Розмір",
    "Scale": "Масштаб",
    "Zoom": "Масштаб",
    "Pan": "Переміщення",
    "Scroll": "Прокрутка",
    "Navigate": "Навігація",
    "View": "Перегляд",
    "Display": "Відображення",
    "Render": "Рендеринг",
    "Draw": "Малювання",
    "Paint": "Малювання",
    "Sketch": "Ескіз",
    "Design": "Дизайн",
    "Theme": "Тема",
    "Mode": "Режим",
    "Type": "Тип",
    "Kind": "Вид",
    "Order": "Порядок",
    "Arrange": "Впорядкувати",
    "Organize": "Організувати",
    "Group": "Група",
    "Ungroup": "Розгрупувати",
    "Pack": "Пакет",
    "Bundle": "Пакет",
    "Package": "Пакет",
    "Module": "Модуль",
    "Component": "Компонент",
    "Element": "Елемент",
    "Item": "Елемент",
    "Object": "Об'єкт",
    "Subject": "Об'єкт",
    "Target": "Ціль",
    "Source": "Джерело",
    "Origin": "Початок",
    "Base": "База",
    "Root": "Корінь",
    "Top": "Верх",
    "Bottom": "Низ",
    "Left": "Ліво",
    "Right": "Право",
    "Up": "Вгору",
    "Down": "Вниз",
    "Forward": "Вперед",
    "Backward": "Назад",
    "Next": "Наступний",
    "Previous": "Попередній",
    "First": "Перший",
    "Last": "Останній",
    "Begin": "Початок",
    "End": "Кінець",
    "Start": "Почати",
    "Finish": "Кінець",
    "Complete": "Завершити",
    "Done": "Готово",
    "Ready": "Готовий",
    "Active": "Активний",
    "Inactive": "Неактивний",
    "Enabled": "Увімкнено",
    "Disabled": "Вимкнено",
    "On": "Увімкнуто",
    "Off": "Вимкнуто",
    "True": "Так",
    "False": "Ні",
    "Yes": "Так",
    "No": "Ні",
    "OK": "Гаразд",
    "Cancel": "Скасувати",
    "Confirm": "Підтвердити",
    "Accept": "Прийняти",
    "Reject": "Відхилити",
    "Skip": "Пропустити",
    "Retry": "Повторити",
    "Fail": "Помилка",
    "Error": "Помилка",
    "Warning": "Попередження",
    "Help": "Допомога",
    "About": "Про",
    "Settings": "Налаштування",
    "Options": "Опції",
    "Preferences": "Налаштування",
    "Config": "Конфігурація",
    "Parameter": "Параметр",
    "Argument": "Аргумент",
    "Value": "Значення",
    "Input": "Вхід",
    "Output": "Вихід",
    "Inputs": "Входи",
    "Outputs": "Виходи",
    "Feed": "Вхід",
    "Destination": "Призначення",
    "Connection": "Зв'язок",
    "Link": "Зв'язок",
    "Port": "Порт",
    "Socket": "Сокет",
    "Slot": "Слот",
    "Stream": "Потік",
    "Track": "Трек",
    "Timeline": "Хронолінг",
    "Frame": "Кадр",
    "Scene": "Сцена",
    "Camera": "Камера",
    "Light": "Світло",
    "Material": "Матеріал",
    "Texture": "Текстура",
    "Shader": "Шейдер",
    "Vertex": "Вершина",
    "Polygon": "Полігон",
    "Mesh": "Меш",
    "Point": "Точка",
    "Line": "Лінія",
    "Circle": "Коло",
    "Square": "Квадрат",
    "Triangle": "Трикутник",
    "Rectangle": "Прямокутник",
    "Angle": "Кут",
    "Distance": "Відстань",
    "Length": "Довжина",
    "Width": "Ширина",
    "Height": "Висота",
    "Area": "Площа",
    "Volume": "Об'єм",
    "Weight": "Вага",
    "Mass": "Маса",
    "Force": "Сила",
    "Energy": "Енергія",
    "Power": "Потужність",
    "Speed": "Швидкість",
    "Velocity": "Швидкість",
    "Acceleration": "Прискорення",
    "Direction": "Напрям",
    "Position": "Позиція",
    "Rotation": "Обертання",
    "Translation": "Переклад",
    "Matrix": "Матриця",
    "Vector": "Вектор",
    "Tensor": "Тензор",
    "Scalar": "Скаляр",
    "Array": "Масив",
    "List": "Список",
    "Dictionary": "Словник",
    "Map": "Карта",
    "Set": "Множина",
    "Tuple": "Кортеж",
    "String": "Рядок",
    "Integer": "Ціле число",
    "Float": "Дробове число",
    "Boolean": "Логічний",
    "Number": "Число",
    "Date": "Дата",
    "Time": "Час",
    "Duration": "Тривалість",
    "Period": "Період",
    "Frequency": "Частота",
    "Rate": "Швидкість",
    "Ratio": "Відношення",
    "Proportion": "Пропорція",
    "Percentage": "Відсоток",
    "Probability": "Ймовірність",
    "Random": "Випадковий",
    "Seed": "Сід",
    "Signal": "Сигнал",
    "Data": "Дані",
    "Metadata": "Метадані",
    "Header": "Заголовок",
    "Body": "Тіло",
    "Content": "Вміст",
    "Code": "Код",
    "Script": "Скрипт",
    "Program": "Програма",
    "Application": "Додаток",
    "System": "Система",
    "Network": "Мережа",
    "Server": "Сервер",
    "Client": "Клієнт",
    "Database": "База даних",
    "Query": "Запит",
    "Command": "Команда",
    "Action": "Дія",
    "Event": "Подія",
    "Message": "Повідомлення",
    "Notification": "Сповіщення",
    "Alert": "Сповіщення",
    "Exception": "Виняток",
    "Failure": "Невдача",
    "Success": "Успіх",
    "Complete": "Завершено",
    "Incomplete": "Незавершено",
    "Pending": "Очікує",
    "Processing": "Обробка",
    "Waiting": "Очікування",
    "Running": "Виконання",
    "Stopped": "Зупинено",
    "Paused": "Призупинено",
    "Resumed": "Відновлено",
    "Started": "Розпочато",
    "Finished": "Завершено",
    "Canceled": "Скасовано",
    "Failed": "Помилка",
    "Succeeded": "Успішно",
    "Aborted": "Перервано",
    "Terminated": "Завершено",
    "Killed": "Вбито",
    "Alive": "Живий",
    "Dead": "Мертвий",
    "Locked": "Заблоковано",
    "Unlocked": "Розблоковано",
    "Connected": "Підключено",
    "Disconnected": "Відключено",
    "Online": "Онлайн",
    "Offline": "Офлайн",
    "Available": "Доступний",
    "Unavailable": "Недоступний",
    "Busy": "Зайнятий",
    "Idle": "Пропускна здатність",
    "Loading": "Завантаження",
    "Saving": "Збереження",
    "Uploading": "Завантаження",
    "Downloading": "Завантаження",
    "Installing": "Встановлення",
    "Uninstalling": "Видалення",
    "Configuring": "Налаштування",
    "Building": "Збудова",
    "Compiling": "Компіляція",
    "Executing": "Виконання",
    "Handling": "Обробка",
    "Managing": "Керування",
    "Controlling": "Керування",
    "Monitoring": "Моніторинг",
    "Tracking": "Відстеження",
    "Logging": "Логування",
    "Recording": "Запис",
    "Capturing": "Захоплення",
    "Extracting": "Виділення",
    "Inserting": "Вставка",
    "Adding": "Додавання",
    "Removing": "Видалення",
    "Deleting": "Видалення",
    "Creating": "Створення",
    "Destroying": "Знищення",
    "Making": "Створення",
    "Building": "Збудова",
    "Constructing": "Створення",
    "Forming": "Формування",
    "Shaping": "Формування",
    "Sizing": "Розмір",
    "Scaling": "Масштаб",
    "Zooming": "Масштаб",
    "Panning": "Переміщення",
    "Scrolling": "Прокрутка",
    "Navigating": "Навігація",
    "Browsing": "Огляд",
    "Viewing": "Перегляд",
    "Displaying": "Відображення",
    "Rendering": "Рендеринг",
    "Drawing": "Малювання",
    "Painting": "Малювання",
    "Sketching": "Ескіз",
    "Designing": "Дизайн",
    "Styling": "Стилізація",
    "Theming": "Темізація",
    "Typing": "Введення",
    "Editing": "Редагування",
    "Copying": "Копіювання",
    "Pasting": "Вставка",
    "Cutting": "Вирізання",
    "Duplicating": "Дублювання",
    "Cloning": "Клонування",
    "Moving": "Рух",
    "Aligning": "Вирівнювання",
    "Centering": "Центрування",
    "Fitting": "Підлаштування",
    "Filling": "Заповнення",
    "Expanding": "Розгортання",
    "Collapsing": "Згортання",
    "Folding": "Складання",
    "Unfolding": "Розгортання",
    "Importing": "Імпорт",
    "Exporting": "Експорт",
    "Uploading": "Завантаження",
    "Downloading": "Завантаження",
    "Syncing": "Синхронізація",
    "Updating": "Оновлення",
    "Refreshing": "Оновлення",
    "Reloading": "Перезавантаження",
    "Restarting": "Перезапуск",
    "Rebooting": "Перезавантаження",
}

# Технічні терміни для полів вводу/виводу
TECHNICAL_TERMS = {
    # Загальні технічні терміни
    'model': 'Модель',
    'noise': 'Шум',
    'sigmas': 'Сигми',
    'latent_image': 'Латентне зображення',
    'images': 'Зображення',
    'factor': 'Коефіцієнт',
    'strength': 'Сила',
    'steps': 'Кроки',
    'denoise': 'Денойз',
    'model_type': 'Тип моделі',
    'clip': 'CLIP',
    'vae': 'VAE',
    'seed': 'Сід',
    'control_net': 'ControlNet',
    'image': 'Зображення',
    'mask': 'Маска',
    'conditioning': 'Кондиціювання',
    'positive': 'Позитивне',
    'negative': 'Негативне',
    'width': 'Ширина',
    'height': 'Висота',
    'batch_size': 'Розмір партії',
    'samples': 'Семпли',
    'latent': 'Латент',
    'conditioning_strength': 'Сила кондиціювання',
    'min_cfg': 'Мін CFG',
    'cfg': 'CFG',
    'sampler_name': 'Назва семплера',
    'scheduler': 'Розклад',
    'guidance': 'Напрям',
    'refiner': 'Рефайнер',
    'upscale_ratio': 'Коефіцієнт масштабування',
    'residual': 'Залишок',
    'weight': 'Вага',
    'bias': 'Зміщення',
    'kernel_size': 'Розмір ядра',
    'stride': 'Крок',
    'padding': 'Відступ',
    'dilation': 'Дилатація',
    'groups': 'Групи',
    'channels': 'Канали',
    'features': 'Особливості',
    'units': 'Одиниці',
    'activation': 'Активація',
    'dropout': 'Дропаут',
    'learning_rate': 'Швидкість навчання',
    'epochs': 'Епохи',
    'batch': 'Партія',
    'shuffle': 'Перемішати',
    'validation': 'Валідація',
    'test': 'Тест',
    'train': 'Навчання',
    'evaluate': 'Оцінити',
    'predict': 'Передбачити',
    'generate': 'Генерувати',
    'transform': 'Трансформувати',
    'process': 'Обробити',
    'analyze': 'Аналізувати',
    'detect': 'Виявити',
    'segment': 'Сегментувати',
    'track': 'Відстежувати',
    'estimate': 'Оцінити',
    'measure': 'Виміряти',
    'calculate': 'Розрахувати',
    'compute': 'Обчислити',
    'render': 'Рендерити',
    'draw': 'Малювати',
    'paint': 'Малювати',
    'edit': 'Редагувати',
    'modify': 'Змінити',
    'adjust': 'Налаштувати',
    'optimize': 'Оптимізувати',
    'improve': 'Покращити',
    'enhance': 'Посилити',
    'reduce': 'Зменшити',
    'increase': 'Збільшити',
    'maintain': 'Підтримувати',
    'preserve': 'Зберегти',
    'restore': 'Відновити',
    'repair': 'Відремонтувати',
    'clean': 'Очистити',
    'filter': 'Фільтрувати',
    'sort': 'Сортувати',
    'organize': 'Організувати',
    'group': 'Групувати',
    'split': 'Розділити',
    'merge': 'Об\'єднати',
    'combine': 'Комбінувати',
    'separate': 'Відокремити',
    'isolate': 'Ізольований',
    'connect': 'Підключити',
    'disconnect': 'Відключити',
    'enable': 'Увімкнути',
    'disable': 'Вимкнути',
    'activate': 'Активувати',
    'deactivate': 'Деактивувати',
    'start': 'Почати',
    'stop': 'Зупинити',
    'pause': 'Пауза',
    'resume': 'Відновити',
    'restart': 'Перезапустити',
    'reset': 'Скинути',
    'clear': 'Очистити',
    'fill': 'Заповнити',
    'empty': 'Порожній',
    'add': 'Додати',
    'remove': 'Видалити',
    'insert': 'Вставити',
    'delete': 'Видалити',
    'replace': 'Замінити',
    'swap': 'Поміняти',
    'move': 'Рухати',
    'copy': 'Копіювати',
    'paste': 'Вставити',
    'cut': 'Вирізати',
    'duplicate': 'Дублювати',
    'clone': 'Клонувати',
    'rotate': 'Повернути',
    'scale': 'Масштаб',
    'flip': 'Відзеркалити',
    'mirror': 'Дзеркало',
    'skew': 'Скіс',
    'distort': 'Дисторція',
    'warp': 'Викривлення',
    'bend': 'Згинається',
    'twist': 'Крутити',
    
    # Текстові поля
    'text': 'Текст',
    'texts': 'Тексти',
    'prefix': 'Префікс',
    'suffix': 'Суфікс',
    'prompt': 'Промпт',
    'prompts': 'Промпти',
    'negative_prompt': 'Негативний промпт',
    'caption': 'Підпис',
    'description': 'Опис',
    'title': 'Заголовок',
    'subtitle': 'Підзаголовок',
    
    # Числові поля
    'value': 'Значення',
    'min_value': 'Мін значення',
    'max_value': 'Макс значення',
    'default_value': 'За замовчуванням',
    'current_value': 'Поточне значення',
    'target_value': 'Цільове значення',
    'threshold': 'Поріг',
    'limit': 'Ліміт',
    'count': 'Кількість',
    'amount': 'Сума',
    'size': 'Розмір',
    'rate': 'Швидкість',
    'ratio': 'Відношення',
    'percentage': 'Відсоток',
    
    # Спеціальні поля
    'input': 'Вхід',
    'output': 'Вихід',
    'inputs': 'Входи',
    'outputs': 'Виходи',
    'data': 'Дані',
    'content': 'Вміст',
    'body': 'Тіло',
    'header': 'Заголовок',
    'footer': 'Низ',
    'top': 'Верх',
    'bottom': 'Низ',
    'left': 'Ліво',
    'right': 'Право',
    'center': 'Центр',
    'middle': 'Середина',
    'start': 'Початок',
    'end': 'Кінець',
    'begin': 'Початок',
    'finish': 'Кінець',
    'first': 'Перший',
    'last': 'Останній',
    'next': 'Наступний',
    'previous': 'Попередній',
    'current': 'Поточний',
    'target': 'Ціль',
    'source': 'Джерело',
    'origin': 'Походження',
    'base': 'База',
    'root': 'Корінь',
    
    # Типи даних
    'string': 'Рядок',
    'integer': 'Ціле число',
    'float': 'Дробове число',
    'boolean': 'Логічний',
    'number': 'Число',
    'array': 'Масив',
    'list': 'Список',
    'dict': 'Словник',
    'map': 'Карта',
    'set': 'Множина',
    'tuple': 'Кортеж',
    
    # Час та дата
    'date': 'Дата',
    'time': 'Час',
    'datetime': 'Дата і час',
    'timestamp': 'Відмітка часу',
    'duration': 'Тривалість',
    'period': 'Період',
    'interval': 'Інтервал',
    
    # Стан та режим
    'state': 'Стан',
    'mode': 'Режим',
    'status': 'Статус',
    'flag': 'Прапорець',
    'option': 'Опція',
    'setting': 'Налаштування',
    'config': 'Конфігурація',
    'parameter': 'Параметр',
    'argument': 'Аргумент',
    'field': 'Поле',
    'property': 'Властивість',
    'attribute': 'Атрибут',
    
    # UI та навігація
    'menu': 'Меню',
    'button': 'Кнопка',
    'label': 'Мітка',
    'placeholder': 'Заповнювач',
    'hint': 'Підказка',
    'help': 'Допомога',
    'info': 'Інформація',
    'warning': 'Попередження',
    'error': 'Помилка',
    'success': 'Успіх',
    'failure': 'Невдача',
    'progress': 'Прогрес',
    'loading': 'Завантаження',
    'saving': 'Збереження',
    'processing': 'Обробка',
    'waiting': 'Очікування',
    'running': 'Виконання',
    'stopped': 'Зупинено',
    'paused': 'Пауза',
    'resumed': 'Відновлено',
    'started': 'Розпочато',
    'finished': 'Завершено',
    'canceled': 'Скасовано',
    'failed': 'Помилка',
    'succeeded': 'Успішно',
    
    # Файли та шляхи
    'file': 'Файл',
    'path': 'Шлях',
    'directory': 'Каталог',
    'folder': 'Папка',
    'name': 'Назва',
    'filename': 'Назва файлу',
    'filepath': 'Шлях до файлу',
    'url': 'URL',
    'uri': 'URI',
    
    # Спеціальні технічні терміни ComfyUI
    'latent_image': 'Латентне зображення',
    'upscale_model': 'Модель масштабування',
    'control_net_model': 'Модель ControlNet',
    'clip_skip': 'CLIP skip',
    'noise_offset': 'Зсув шуму',
    'noise_scale': 'Масштаб шуму',
    'noise_decay': 'Згасання шуму',
    'noise_strength': 'Сила шуму',
    'noise_seed': 'Сід шуму',
    'latent_format': 'Формат латенту',
    'latent_channels': 'Канали латенту',
    'latent_width': 'Ширина латенту',
    'latent_height': 'Висота латенту',
    'sample_width': 'Ширина семплу',
    'sample_height': 'Висота семплу',
    'sample_channels': 'Канали семплу',
    'output_format': 'Формат виводу',
    'save_image': 'Зберегти зображення',
    'image_quality': 'Якість зображення',
    'image_compression': 'Стиснення зображення',
    'image_resolution': 'Роздільна здатність',
    'image_scale': 'Масштаб зображення',
    'image_crop': 'Обрізання зображення',
    'image_resize': 'Зміна розміру зображення',
    'image_rotate': 'Поворот зображення',
    'image_flip': 'Віддзеркалення зображення',
    'image_mirror': 'Дзеркало зображення',
    'image_blur': 'Розмиття зображення',
    'image_sharpen': 'Зострення зображення',
    'image_denoise': 'Денойз зображення',
    'image_color': 'Колір зображення',
    'image_brightness': 'Яскравість зображення',
    'image_contrast': 'Контраст зображення',
    'image_hue': 'Відтінок зображення',
    'image_saturation': 'Насиченість зображення',
    'image_gamma': 'Гама зображення',
    'image_exposure': 'Експозиція зображення',
    'image_shadow': 'Тінь зображення',
    'image_highlight': 'Світлина зображення',
    'image_depth': 'Глибина зображення',
    'image_normal': 'Нормаль зображення',
    'image_edge': 'Край зображення',
    'image_pose': 'Поза зображення',
    'image_segmentation': 'Сегментація зображення',
    'image_detection': 'Виявлення зображення',
    'image_tracking': 'Відстеження зображення',
    'image_flow': 'Потік зображення',
    'image_histogram': 'Гістограма зображення',
    'image_curve': 'Крива зображення',
    'image_gradient': 'Градієнт зображення',
    'image_grid': 'Сітка зображення',
    'image_tile': 'Плитка зображення',
    'image_stamp': 'Штамп зображення',
    'image_watermark': 'Водяний знак зображення',
    'image_inpaint': 'Інпейнтинг зображення',
    'image_outpaint': 'Аутпейнтинг зображення',
    'image_fill': 'Заповнення зображення',
    'image_remove': 'Видалення зображення',
    'image_background': 'Фон зображення',
    'image_foreground': 'Передній план зображення',
    'image_alpha': 'Альфа зображення',
    'image_channel': 'Канал зображення',
    'image_layer': 'Шар зображення',
    'image_stack': 'Стек зображень',
    'image_concatenate': 'Конкатенація зображень',
    'image_interleave': 'Чергування зображень',
    'image_shuffle': 'Перемішування зображень',
    'image_sort': 'Сортування зображень',
    'image_filter': 'Фільтр зображень',
    'image_threshold': 'Поріг зображень',
    'image_quantize': 'Квантизація зображень',
    'image_dequantize': 'Деквантизація зображень',
    'image_compress': 'Стиснення зображень',
    'image_decompress': 'Розпакування зображень',
    'image_encrypt': 'Шифрування зображень',
    'image_decrypt': 'Розшифрування зображень',
    'image_hash': 'Хеш зображень',
    'image_sign': 'Підпис зображень',
    'image_verify': 'Перевірка зображень',
    'image_validate': 'Валідація зображень',
    'image_test': 'Тест зображень',
    'image_debug': 'Налагодження зображень',
    'image_info': 'Інформація про зображення',
    'image_status': 'Статус зображення',
    'image_progress': 'Прогрес зображення',
    'image_history': 'Історія зображення',
    'image_cache': 'Кеш зображень',
    'image_buffer': 'Буфер зображень',
    'image_queue': 'Черга зображень',
    'image_pause': 'Пауза зображень',
    'image_resume': 'Відновлення зображень',
    'image_stop': 'Зупинка зображень',
    'image_start': 'Старт зображень',
    'image_reset': 'Скидання зображень',
    'image_clear': 'Очищення зображень',
    'image_set': 'Встановлення зображень',
    'image_get': 'Отримання зображень',
    'image_read': 'Читання зображень',
    'image_write': 'Запис зображень',
    'image_open': 'Відкриття зображень',
    'image_close': 'Закриття зображень',
    'image_show': 'Показ зображень',
    'image_hide': 'Приховання зображень',
    'image_enable': 'Увімкнення зображень',
    'image_disable': 'Вимкнення зображень',
    'image_toggle': 'Перемикання зображень',
    'image_switch': 'Перемикання зображень',
    'image_select': 'Вибір зображень',
    'image_deselect': 'Скасування вибору зображень',
    'image_pick': 'Вибір зображень',
    'image_choose': 'Обрання зображень',
    'image_browse': 'Огляд зображень',
    'image_search': 'Пошук зображень',
    'image_find': 'Знаходження зображень',
    'image_replace': 'Заміна зображень',
    'image_edit': 'Редагування зображень',
    'image_copy': 'Копіювання зображень',
    'image_paste': 'Вставлення зображень',
    'image_cut': 'Вирізання зображень',
    'image_duplicate': 'Дублювання зображень',
    'image_clone': 'Клонування зображень',
    'image_move': 'Рух зображень',
    'image_align': 'Вирівнювання зображень',
    'image_center': 'Центрування зображень',
    'image_fit': 'Підлаштування зображень',
    'image_expand': 'Розгортання зображень',
    'image_collapse': 'Згортання зображень',
    'image_fold': 'Складання зображень',
    'image_unfold': 'Розгортання зображень',
    'image_import': 'Імпорт зображень',
    'image_export': 'Експорт зображень',
    'image_upload': 'Завантаження зображень',
    'image_download': 'Завантаження зображень',
    'image_sync': 'Синхронізація зображень',
    'image_update': 'Оновлення зображень',
    'image_refresh': 'Оновлення зображень',
    'image_reload': 'Перезавантаження зображень',
    'image_restart': 'Перезапуск зображень',
    'image_reboot': 'Перезавантаження зображень',
    'image_install': 'Встановлення зображень',
    'image_uninstall': 'Видалення зображень',
    'image_configure': 'Налаштування зображень',
    'image_setup': 'Налаштування зображень',
    'image_init': 'Ініціалізація зображень',
    'image_initialize': 'Ініціалізація зображень',
    'image_build': 'Збудова зображень',
    'image_compile': 'Компіляція зображень',
    'image_run': 'Запуск зображень',
    'image_execute': 'Виконання зображень',
    'image_process': 'Обробка зображень',
    'image_handle': 'Обробка зображень',
    'image_manage': 'Керування зображеннями',
    'image_control': 'Керування зображеннями',
    'image_monitor': 'Моніторинг зображень',
    'image_track': 'Відстеження зображень',
    'image_log': 'Логування зображень',
    'image_record': 'Запис зображень',
    'image_capture': 'Захоплення зображень',
    'image_extract': 'Виділення зображень',
    'image_insert': 'Вставка зображень',
    'image_add': 'Додавання зображень',
    'image_remove': 'Видалення зображень',
    'image_delete': 'Видалення зображень',
    'image_create': 'Створення зображень',
    'image_destroy': 'Знищення зображень',
    'image_make': 'Створення зображень',
    'image_build': 'Збудова зображень',
    'image_construct': 'Створення зображень',
    'image_form': 'Формування зображень',
    'image_shape': 'Формування зображень',
    'image_size': 'Розмір зображень',
    'image_scale': 'Масштаб зображень',
    'image_zoom': 'Масштаб зображень',
    'image_pan': 'Переміщення зображень',
    'image_scroll': 'Прокрутка зображень',
    'image_navigate': 'Навігація зображень',
    'image_view': 'Перегляд зображень',
    'image_display': 'Відображення зображень',
    'image_render': 'Рендеринг зображень',
    'image_draw': 'Малювання зображень',
    'image_paint': 'Малювання зображень',
    'image_sketch': 'Ескіз зображень',
    'image_design': 'Дизайн зображень',
    'image_theme': 'Тема зображень',
    'image_mode': 'Режим зображень',
    'image_type': 'Тип зображень',
    'image_kind': 'Вид зображень',
    'image_order': 'Порядок зображень',
    'image_arrange': 'Впорядкування зображень',
    'image_organize': 'Організація зображень',
    'image_group': 'Групування зображень',
    'image_ungroup': 'Розгрупування зображень',
    'image_pack': 'Пакування зображень',
    'image_bundle': 'Пакування зображень',
    'image_package': 'Пакування зображень',
    'image_module': 'Модуль зображень',
    'image_component': 'Компонент зображень',
    'image_element': 'Елемент зображень',
    'image_item': 'Елемент зображень',
    'image_object': 'Об\'єкт зображень',
    'image_subject': 'Об\'єкт зображень',
    'image_target': 'Ціль зображень',
    'image_source': 'Джерело зображень',
    'image_origin': 'Походження зображень',
    'image_base': 'База зображень',
    'image_root': 'Корінь зображень',
    'image_top': 'Верх зображень',
    'image_bottom': 'Низ зображень',
    'image_left': 'Ліво зображень',
    'image_right': 'Право зображень',
    'image_up': 'Вгору зображень',
    'image_down': 'Вниз зображень',
    'image_forward': 'Вперед зображень',
    'image_backward': 'Назад зображень',
    'image_next': 'Наступний зображень',
    'image_previous': 'Попередній зображень',
    'image_first': 'Перший зображень',
    'image_last': 'Останній зображень',
    'image_begin': 'Початок зображень',
    'image_end': 'Кінець зображень',
    'image_start': 'Старт зображень',
    'image_finish': 'Кінець зображень',
    'image_complete': 'Завершення зображень',
    'image_done': 'Готово зображень',
    'image_ready': 'Готовий зображень',
    'image_active': 'Активний зображень',
    'image_inactive': 'Неактивний зображень',
    'image_enabled': 'Увімкнено зображень',
    'image_disabled': 'Вимкнено зображень',
    'image_on': 'Увімкнуто зображень',
    'image_off': 'Вимкнуто зображень',
    'image_true': 'Так зображень',
    'image_false': 'Ні зображень',
    'image_yes': 'Так зображень',
    'image_no': 'Ні зображень',
    'image_ok': 'Гаразд зображень',
    'image_cancel': 'Скасування зображень',
    'image_confirm': 'Підтвердження зображень',
    'image_accept': 'Прийняття зображень',
    'image_reject': 'Відхилення зображень',
    'image_skip': 'Пропуск зображень',
    'image_retry': 'Повторення зображень',
    'image_fail': 'Помилка зображень',
    'image_error': 'Помилка зображень',
    'image_warning': 'Попередження зображень',
    'image_help': 'Допомога зображень',
    'image_about': 'Про зображення',
    'image_settings': 'Налаштування зображень',
    'image_options': 'Опції зображень',
    'image_preferences': 'Налаштування зображень',
    'image_config': 'Конфігурація зображень',
    'image_parameter': 'Параметр зображень',
    'image_argument': 'Аргумент зображень',
    'image_value': 'Значення зображень',
    'image_input': 'Вхід зображень',
    'image_output': 'Вихід зображень',
    'image_inputs': 'Входи зображень',
    'image_outputs': 'Виходи зображень',
    'image_feed': 'Вхід зображень',
    'image_destination': 'Призначення зображень',
    'image_connection': 'Зв\'язок зображень',
    'image_link': 'Зв\'язок зображень',
    'image_port': 'Порт зображень',
    'image_socket': 'Сокет зображень',
    'image_slot': 'Слот зображень',
    'image_stream': 'Потік зображень',
    'image_track': 'Трек зображень',
    'image_timeline': 'Хронолінг зображень',
    'image_frame': 'Кадр зображень',
    'image_scene': 'Сцена зображень',
    'image_camera': 'Камера зображень',
    'image_light': 'Світло зображень',
    'image_material': 'Матеріал зображень',
    'image_texture': 'Текстура зображень',
    'image_shader': 'Шейдер зображень',
    'image_vertex': 'Вершина зображень',
    'image_polygon': 'Полігон зображень',
    'image_mesh': 'Меш зображень',
    'image_point': 'Точка зображень',
    'image_line': 'Лінія зображень',
    'image_circle': 'Коло зображень',
    'image_square': 'Квадрат зображень',
    'image_triangle': 'Трикутник зображень',
    'image_rectangle': 'Прямокутник зображень',
    'image_angle': 'Кут зображень',
    'image_distance': 'Відстань зображень',
    'image_length': 'Довжина зображень',
    'image_width': 'Ширина зображень',
    'image_height': 'Висота зображень',
    'image_area': 'Площа зображень',
    'image_volume': 'Об\'єм зображень',
    'image_weight': 'Вага зображень',
    'image_mass': 'Маса зображень',
    'image_force': 'Сила зображень',
    'image_energy': 'Енергія зображень',
    'image_power': 'Потужність зображень',
    'image_speed': 'Швидкість зображень',
    'image_velocity': 'Швидкість зображень',
    'image_acceleration': 'Прискорення зображень',
    'image_direction': 'Напрям зображень',
    'image_position': 'Позиція зображень',
    'image_rotation': 'Обертання зображень',
    'image_translation': 'Переклад зображень',
    'image_matrix': 'Матриця зображень',
    'image_vector': 'Вектор зображень',
    'image_tensor': 'Тензор зображень',
    'image_scalar': 'Скаляр зображень',
    'image_array': 'Масив зображень',
    'image_list': 'Список зображень',
    'image_dict': 'Словник зображень',
    'image_map': 'Карта зображень',
    'image_set': 'Множина зображень',
    'image_tuple': 'Кортеж зображень',
    'image_string': 'Рядок зображень',
    'image_integer': 'Ціле число зображень',
    'image_float': 'Дробове число зображень',
    'image_boolean': 'Логічний зображень',
    'image_number': 'Число зображень',
    'image_date': 'Дата зображень',
    'image_time': 'Час зображень',
    'image_duration': 'Тривалість зображень',
    'image_period': 'Період зображень',
    'image_frequency': 'Частота зображень',
    'image_rate': 'Швидкість зображень',
    'image_ratio': 'Відношення зображень',
    'image_proportion': 'Пропорція зображень',
    'image_percentage': 'Відсоток зображень',
    'image_probability': 'Ймовірність зображень',
    'image_random': 'Випадковий зображень',
    'image_seed': 'Сід зображень',
    'image_signal': 'Сигнал зображень',
    'image_data': 'Дані зображень',
    'image_metadata': 'Метадані зображень',
    'image_header': 'Заголовок зображень',
    'image_body': 'Тіло зображень',
    'image_content': 'Вміст зображень',
    'image_code': 'Код зображень',
    'image_script': 'Скрипт зображень',
    'image_program': 'Програма зображень',
    'image_application': 'Додаток зображень',
    'image_system': 'Система зображень',
    'image_network': 'Мережа зображень',
    'image_server': 'Сервер зображень',
    'image_client': 'Клієнт зображень',
    'image_database': 'База даних зображень',
    'image_query': 'Запит зображень',
    'image_command': 'Команда зображень',
    'image_action': 'Дія зображень',
    'image_event': 'Подія зображень',
    'image_message': 'Повідомлення зображень',
    'image_notification': 'Сповіщення зображень',
    'image_alert': 'Сповіщення зображень',
    'image_exception': 'Виняток зображень',
    'image_failure': 'Невдача зображень',
    'image_success': 'Успіх зображень',
    'image_complete': 'Завершено зображень',
    'image_incomplete': 'Незавершено зображень',
    'image_pending': 'Очікує зображень',
    'image_processing': 'Обробка зображень',
    'image_waiting': 'Очікування зображень',
    'image_running': 'Виконання зображень',
    'image_stopped': 'Зупинено зображень',
    'image_paused': 'Призупинено зображень',
    'image_resumed': 'Відновлено зображень',
    'image_started': 'Розпочато зображень',
    'image_finished': 'Завершено зображень',
    'image_canceled': 'Скасовано зображень',
    'image_failed': 'Помилка зображень',
    'image_succeeded': 'Успішно зображень',
    'image_aborted': 'Перервано зображень',
    'image_terminated': 'Завершено зображень',
    'image_killed': 'Вбито зображень',
    'image_alive': 'Живий зображень',
    'image_dead': 'Мертвий зображень',
    'image_locked': 'Заблоковано зображень',
    'image_unlocked': 'Розблоковано зображень',
    'image_connected': 'Підключено зображень',
    'image_disconnected': 'Відключено зображень',
    'image_online': 'Онлайн зображень',
    'image_offline': 'Офлайн зображень',
    'image_available': 'Доступний зображень',
    'image_unavailable': 'Недоступний зображень',
    'image_busy': 'Зайнятий зображень',
    'image_idle': 'Пропускна здатність зображень',
    'image_loading': 'Завантаження зображень',
    'image_saving': 'Збереження зображень',
    'image_uploading': 'Завантаження зображень',
    'image_downloading': 'Завантаження зображень',
    'image_installing': 'Встановлення зображень',
    'image_uninstalling': 'Видалення зображень',
    'image_configuring': 'Налаштування зображень',
    'image_building': 'Збудова зображень',
    'image_compiling': 'Компіляція зображень',
    'image_executing': 'Виконання зображень',
    'image_handling': 'Обробка зображень',
    'image_managing': 'Керування зображеннями',
    'image_controlling': 'Керування зображеннями',
    'image_monitoring': 'Моніторинг зображень',
    'image_tracking': 'Відстеження зображень',
    'image_logging': 'Логування зображень',
    'image_recording': 'Запис зображень',
    'image_capturing': 'Захоплення зображень',
    'image_extracting': 'Виділення зображень',
    'image_inserting': 'Вставка зображень',
    'image_adding': 'Додавання зображень',
    'image_removing': 'Видалення зображень',
    'image_deleting': 'Видалення зображень',
    'image_creating': 'Створення зображень',
    'image_destroying': 'Знищення зображень',
    'image_making': 'Створення зображень',
    'image_building': 'Збудова зображень',
    'image_constructing': 'Створення зображень',
    'image_forming': 'Формування зображень',
    'image_shaping': 'Формування зображень',
    'image_sizing': 'Розмір зображень',
    'image_scaling': 'Масштаб зображень',
    'image_zooming': 'Масштаб зображень',
    'image_panning': 'Переміщення зображень',
    'image_scrolling': 'Прокрутка зображень',
    'image_navigating': 'Навігація зображень',
    'image_browsing': 'Огляд зображень',
    'image_viewing': 'Перегляд зображень',
    'image_displaying': 'Відображення зображень',
    'image_rendering': 'Рендеринг зображень',
    'image_drawing': 'Малювання зображень',
    'image_painting': 'Малювання зображень',
    'image_sketching': 'Ескіз зображень',
    'image_designing': 'Дизайн зображень',
    'image_styling': 'Стилізація зображень',
    'image_theming': 'Темізація зображень',
    'image_typing': 'Введення зображень',
    'image_editing': 'Редагування зображень',
    'image_copying': 'Копіювання зображень',
    'image_pasting': 'Вставка зображень',
    'image_cutting': 'Вирізання зображень',
    'image_duplicating': 'Дублювання зображень',
    'image_cloning': 'Клонування зображень',
    'image_moving': 'Рух зображень',
    'image_aligning': 'Вирівнювання зображень',
    'image_centering': 'Центрування зображень',
    'image_fitting': 'Підлаштування зображень',
    'image_filling': 'Заповнення зображень',
    'image_expanding': 'Розгортання зображень',
    'image_collapsing': 'Згортання зображень',
    'image_folding': 'Складання зображень',
    'image_unfolding': 'Розгортання зображень',
    'image_importing': 'Імпорт зображень',
    'image_exporting': 'Експорт зображень',
    'image_uploading': 'Завантаження зображень',
    'image_downloading': 'Завантаження зображень',
    'image_syncing': 'Синхронізація зображень',
    'image_updating': 'Оновлення зображень',
    'image_refreshing': 'Оновлення зображень',
    'image_reloading': 'Перезавантаження зображень',
    'image_restarting': 'Перезапуск зображень',
    'image_rebooting': 'Перезавантаження зображень',
}

# Патерни перекладу для речень
SENTENCE_PATTERNS = [
    (r"^(.+?) for (.+)$", r"\2 - \1"),
    (r"^Apply (.+) to (.+)$", r"Застосувати \1 до \2"),
    (r"^Set (.+) to (.+)$", r"Встановити \1 в \2"),
    (r"^Get (.+)$", r"Отримати \1"),
    (r"^Create new (.+)$", r"Створити новий \1"),
    (r"^Load (.+)$", r"Завантажити \1"),
    (r"^Save (.+)$", r"Зберегти \1"),
    (r"^Preview (.+)$", r"Попередній перегляд \1"),
]

def translate_term(term, context=None):
    """Переклад одного терміну або фрази."""
    if not term or not isinstance(term, str):
        return term
    
    # Якщо термін в словнику - використовуємо його
    if term in TERM_TRANSLATIONS:
        return TERM_TRANSLATIONS[term]
    
    # Перевірка патернів
    for pattern, replacement in SENTENCE_PATTERNS:
        match = re.match(pattern, term, re.IGNORECASE)
        if match:
            translated = re.sub(pattern, replacement, term, flags=re.IGNORECASE)
            return translated
    
    # Якщо це велике слово з великої літери - спробуємо перекласти кореневе слово
    if term[0].isupper() and ' ' not in term:
        lower_term = term.lower()
        if lower_term in TERM_TRANSLATIONS:
            translated = TERM_TRANSLATIONS[lower_term]
            return translated[0].upper() + translated[1:]
    
    # Якщо це шлях категорії (наприклад, "image/adjust/color")
    if '/' in term:
        parts = term.split('/')
        translated_parts = [translate_term(p) if p else p for p in parts]
        return '/'.join(translated_parts)
    
    # Якщо це параметр з advanced або іншими ключовими словами
    if term.startswith("advanced") or term == "advanced":
        return "розширені"
    
    # Переклад технічних термінів (input/output field names)
    if term in TECHNICAL_TERMS:
        return TECHNICAL_TERMS[term]
    
    # За замовчуванням - повертаємо оригінал
    return term

def translate_node_name(node_id):
    """Переклад назви вузла з формату AddNoise -> Додавання шуму."""
    if not node_id:
        return ""
    
    # Розбиваємо CamelCase на слова
    words = re.findall(r'[A-Z][a-z]+', node_id)
    
    if not words:
        return node_id
    
    # Перекладаємо кожне слово
    translated_words = [translate_term(w) for w in words]
    
    # Об'єднуємо слова
    result = ' '.join(translated_words)
    
    return result

def translate_tooltip(tooltip):
    """Переклад підказки."""
    if not tooltip or not isinstance(tooltip, str):
        return tooltip
    
    return translate_term(tooltip)

def translate_node_def(node_id, node_def):
    """Переклад одного вузла."""
    if not isinstance(node_def, dict):
        return node_def
    
    result = {}
    
    # Переклад display_name (якщо є)
    if "display_name" in node_def:
        result["display_name"] = translate_node_name(node_id) if not node_def["display_name"] else node_def["display_name"]
    
    # Переклад description (якщо є)
    if "description" in node_def and node_def["description"]:
        result["description"] = translate_term(node_def["description"])
    
    # Переклад inputs
    if "inputs" in node_def and isinstance(node_def["inputs"], dict):
        result["inputs"] = {}
        for input_name, input_def in node_def["inputs"].items():
            if isinstance(input_def, dict):
                result["inputs"][input_name] = {}
                
                # Переклад name (якщо порожній або технічний термін)
                if "name" in input_def:
                    original_name = input_def["name"]
                    if not original_name or original_name in TECHNICAL_TERMS:
                        result["inputs"][input_name]["name"] = translate_term(original_name) if original_name else translate_term(input_name)
                    else:
                        result["inputs"][input_name]["name"] = original_name
                
                # Переклад tooltip (якщо є)
                if "tooltip" in input_def and input_def["tooltip"]:
                    result["inputs"][input_name]["tooltip"] = translate_tooltip(input_def["tooltip"])
                elif not original_name:
                    # Якщо tooltip порожній, спробуємо перекласти назву поля
                    result["inputs"][input_name]["tooltip"] = translate_term(input_name)
                
                # Копіюємо інші поля без змін
                for key, value in input_def.items():
                    if key not in ["name", "tooltip"]:
                        result["inputs"][input_name][key] = value
            else:
                result["inputs"][input_name] = input_def
    
    # Переклад outputs
    if "outputs" in node_def and isinstance(node_def["outputs"], dict):
        result["outputs"] = {}
        for output_id, output_def in node_def["outputs"].items():
            if isinstance(output_def, dict):
                result["outputs"][output_id] = {}
                
                # Переклад name (якщо порожній або технічний термін)
                if "name" in output_def:
                    original_name = output_def["name"]
                    if not original_name or original_name in TECHNICAL_TERMS:
                        result["outputs"][output_id]["name"] = translate_term(original_name) if original_name else f"Вихід {output_id}"
                    else:
                        result["outputs"][output_id]["name"] = original_name
                
                # Переклад tooltip (якщо є)
                if "tooltip" in output_def and output_def["tooltip"]:
                    result["outputs"][output_id]["tooltip"] = translate_tooltip(output_def["tooltip"])
            else:
                result["outputs"][output_id] = output_def
    
    # Копіюємо інші поля без змін
    for key, value in node_def.items():
        if key not in ["display_name", "description", "inputs", "outputs"]:
            result[key] = value
    
    return result

def translate_all_nodes(input_file, output_file):
    """Переклад всіх вузлів у файлі."""
    print(f"Завантаження {input_file}...")
    
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    total_nodes = len(data)
    translated_count = 0
    
    result = {}
    for node_id, node_def in data.items():
        result[node_id] = translate_node_def(node_id, node_def)
        translated_count += 1
        
        # Виводимо прогрес кожні 100 вузлів
        if translated_count % 100 == 0:
            print(f"Перекладено {translated_count}/{total_nodes} вузлів...")
    
    print(f"\nЗбереження перекладу до {output_file}...")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    
    print(f"Готово! Перекладено {translated_count} вузлів.")

def main():
    """Головна функція."""
    # Шляхи до файлів
    base_dir = os.path.dirname(os.path.abspath(__file__))
    input_file = os.path.join(base_dir, "..", "locales", "uk", "nodeDefs.json")
    output_file = os.path.join(base_dir, "..", "locales", "uk", "nodeDefs_translated.json")
    
    # Переклад
    translate_all_nodes(input_file, output_file)
    
    print(f"\nПереклад завершено!")
    print(f"Вихідний файл: {input_file}")
    print(f"Результат збережено в: {output_file}")

if __name__ == "__main__":
    main()
