#!/usr/bin/env python3
"""
Скрипт для автоматичного перекладу main.json на українську мову.
Заповнює порожні значення вже існуючими перекладами або створює нові.
"""
import json
import re
import os

# Словник перекладів для поширених термінів (той самий, що й у translate_node_defs.py)
TERM_TRANSLATIONS = {
    "Load": "Завантажити",
    "Save": "Зберегти",
    "Preview": "Попередній перегляд",
    "Encode": "Кодувати",
    "Decode": "Декодувати",
    "Apply": "Застосувати",
    "Create": "Створити",
    "Generate": "Генерувати",
    "Convert": "Конвертувати",
    "Transform": "Трансформувати",
    "Resize": "Змінити розмір",
    "Crop": "Обрізати",
    "Rotate": "Повернути",
    "Flip": "Відзеркалити",
    "Mirror": "Дзеркало",
    "Blur": "Розмити",
    "Sharpen": "Зостришити",
    "Noise": "Шум",
    "Mask": "Маска",
    "Merge": "Об'єднати",
    "Split": "Розділити",
    "Batch": "Партія",
    "Repeat": "Повторити",
    "Loop": "Цикл",
    "Schedule": "Розклад",
    "Sampler": "Семплер",
    "Sampling": "Семплування",
    "Guide": "Напрям",
    "Condition": "Кондиція",
    "Conditioning": "Кондиціювання",
    "Prompt": "Промпт",
    "Text": "Текст",
    "Image": "Зображення",
    "Video": "Відео",
    "Audio": "Аудіо",
    "Model": "Модель",
    "Latent": "Латент",
    "VAE": "VAE",
    "CLIP": "CLIP",
    "ControlNet": "ControlNet",
    "GLIGEN": "GLIGEN",
    "LoRA": "LoRA",
    "Style": "Стиль",
    "Color": "Колір",
    "Brightness": "Яскравість",
    "Contrast": "Контраст",
    "Hue": "Відтінок",
    "Saturation": "Насиченість",
    "Gamma": "Гама",
    "Exposure": "Експозиція",
    "Shadow": "Тінь",
    "Highlight": "Світлина",
    "Depth": "Глибина",
    "Normal": "Нормаль",
    "Edge": "Край",
    "Pose": "Поза",
    "Segmentation": "Сегментація",
    "Detection": "Виявлення",
    "Tracking": "Відстеження",
    "Flow": "Потік",
    "Histogram": "Гістограма",
    "Curve": "Крива",
    "Gradient": "Градієнт",
    "Grid": "Сітка",
    "Tile": "Плитка",
    "Stamp": "Штамп",
    "Watermark": "Водяний знак",
    "Inpaint": "Інпейнтинг",
    "Outpaint": "Аутпейнтинг",
    "Fill": "Заповнення",
    "Remove": "Видалити",
    "Background": "Фон",
    "Foreground": "Передній план",
    "Alpha": "Альфа",
    "Channel": "Канал",
    "Layer": "Шар",
    "Stack": "Стек",
    "Concatenate": "Конкатенація",
    "Interleave": "Чергування",
    "Shuffle": "Перемішати",
    "Sort": "Сортувати",
    "Filter": "Фільтр",
    "Threshold": "Поріг",
    "Quantize": "Квантизувати",
    "Dequantize": "Деквантизувати",
    "Compress": "Стиснути",
    "Decompress": "Розпакувати",
    "Encrypt": "Шифрувати",
    "Decrypt": "Розшифрувати",
    "Hash": "Хеш",
    "Sign": "Підпис",
    "Verify": "Перевірити",
    "Validate": "Валідувати",
    "Test": "Тест",
    "Debug": "Налагодження",
    "Info": "Інформація",
    "Status": "Статус",
    "Progress": "Прогрес",
    "History": "Історія",
    "Cache": "Кеш",
    "Buffer": "Буфер",
    "Queue": "Черга",
    "Pause": "Пауза",
    "Resume": "Відновити",
    "Stop": "Зупинити",
    "Start": "Почати",
    "Reset": "Скинути",
    "Clear": "Очистити",
    "Set": "Встановити",
    "Get": "Отримати",
    "Read": "Прочитати",
    "Write": "Записати",
    "Open": "Відкрити",
    "Close": "Закрити",
    "Show": "Показати",
    "Hide": "Приховати",
    "Enable": "Увімкнути",
    "Disable": "Вимкнути",
    "Toggle": "Перемкнути",
    "Switch": "Перемкнути",
    "Select": "Вибрати",
    "Deselect": "Скасувати вибір",
    "Pick": "Вибрати",
    "Choose": "Обрати",
    "Browse": "Оглянути",
    "Search": "Пошук",
    "Find": "Знайти",
    "Replace": "Замінити",
    "Edit": "Редагувати",
    "Copy": "Копіювати",
    "Paste": "Вставити",
    "Cut": "Вирізати",
    "Duplicate": "Дублювати",
    "Clone": "Клонувати",
    "Move": "Рухати",
    "Align": "Вирівняти",
    "Center": "Центр",
    "Fit": "Підлаштувати",
    "Expand": "Розгорнути",
    "Collapse": "Згорнути",
    "Fold": "Скласти",
    "Unfold": "Розгорнути",
    "Import": "Імпорт",
    "Export": "Експорт",
    "Upload": "Завантажити",
    "Download": "Завантажити",
    "Sync": "Синхронізувати",
    "Update": "Оновити",
    "Refresh": "Оновити",
    "Reload": "Перезавантажити",
    "Restart": "Перезапустити",
    "Reboot": "Перезавантажити",
    "Install": "Встановити",
    "Uninstall": "Видалити",
    "Configure": "Налаштувати",
    "Setup": "Налаштування",
    "Init": "Ініціалізувати",
    "Initialize": "Ініціалізувати",
    "Build": "Збудувати",
    "Compile": "Компілювати",
    "Run": "Запустити",
    "Execute": "Виконати",
    "Process": "Обробити",
    "Handle": "Обробити",
    "Manage": "Керувати",
    "Control": "Керувати",
    "Monitor": "Моніторинг",
    "Track": "Відстежувати",
    "Log": "Лог",
    "Record": "Записати",
    "Capture": "Захопити",
    "Extract": "Виділити",
    "Insert": "Вставити",
    "Add": "Додати",
    "Remove": "Видалити",
    "Delete": "Видалити",
    "Create": "Створити",
    "Destroy": "Знищити",
    "Make": "Створити",
    "Build": "Збудувати",
    "Construct": "Створити",
    "Form": "Форма",
    "Shape": "Форма",
    "Size": "Розмір",
    "Scale": "Масштаб",
    "Zoom": "Масштаб",
    "Pan": "Переміщення",
    "Scroll": "Прокрутка",
    "Navigate": "Навігація",
    "View": "Перегляд",
    "Display": "Відображення",
    "Render": "Рендеринг",
    "Draw": "Малювання",
    "Paint": "Малювання",
    "Sketch": "Ескіз",
    "Design": "Дизайн",
    "Theme": "Тема",
    "Mode": "Режим",
    "Type": "Тип",
    "Kind": "Вид",
    "Order": "Порядок",
    "Arrange": "Впорядкувати",
    "Organize": "Організувати",
    "Group": "Група",
    "Ungroup": "Розгрупувати",
    "Pack": "Пакет",
    "Bundle": "Пакет",
    "Package": "Пакет",
    "Module": "Модуль",
    "Component": "Компонент",
    "Element": "Елемент",
    "Item": "Елемент",
    "Object": "Об'єкт",
    "Subject": "Об'єкт",
    "Target": "Ціль",
    "Source": "Джерело",
    "Origin": "Початок",
    "Base": "База",
    "Root": "Корінь",
    "Top": "Верх",
    "Bottom": "Низ",
    "Left": "Ліво",
    "Right": "Право",
    "Up": "Вгору",
    "Down": "Вниз",
    "Forward": "Вперед",
    "Backward": "Назад",
    "Next": "Наступний",
    "Previous": "Попередній",
    "First": "Перший",
    "Last": "Останній",
    "Begin": "Початок",
    "End": "Кінець",
    "Start": "Почати",
    "Finish": "Кінець",
    "Complete": "Завершити",
    "Done": "Готово",
    "Ready": "Готовий",
    "Active": "Активний",
    "Inactive": "Неактивний",
    "Enabled": "Увімкнено",
    "Disabled": "Вимкнено",
    "On": "Увімкнуто",
    "Off": "Вимкнуто",
    "True": "Так",
    "False": "Ні",
    "Yes": "Так",
    "No": "Ні",
    "OK": "Гаразд",
    "Cancel": "Скасувати",
    "Confirm": "Підтвердити",
    "Accept": "Прийняти",
    "Reject": "Відхилити",
    "Skip": "Пропустити",
    "Retry": "Повторити",
    "Fail": "Помилка",
    "Error": "Помилка",
    "Warning": "Попередження",
    "Help": "Допомога",
    "About": "Про",
    "Settings": "Налаштування",
    "Options": "Опції",
    "Preferences": "Налаштування",
    "Config": "Конфігурація",
    "Parameter": "Параметр",
    "Argument": "Аргумент",
    "Value": "Значення",
    "Input": "Вхід",
    "Output": "Вихід",
    "Inputs": "Входи",
    "Outputs": "Виходи",
    "Feed": "Вхід",
    "Destination": "Призначення",
    "Connection": "Зв'язок",
    "Link": "Зв'язок",
    "Port": "Порт",
    "Socket": "Сокет",
    "Slot": "Слот",
    "Stream": "Потік",
    "Track": "Трек",
    "Timeline": "Хронолінг",
    "Frame": "Кадр",
    "Scene": "Сцена",
    "Camera": "Камера",
    "Light": "Світло",
    "Material": "Матеріал",
    "Texture": "Текстура",
    "Shader": "Шейдер",
    "Vertex": "Вершина",
    "Polygon": "Полігон",
    "Mesh": "Меш",
    "Point": "Точка",
    "Line": "Лінія",
    "Circle": "Коло",
    "Square": "Квадрат",
    "Triangle": "Трикутник",
    "Rectangle": "Прямокутник",
    "Angle": "Кут",
    "Distance": "Відстань",
    "Length": "Довжина",
    "Width": "Ширина",
    "Height": "Висота",
    "Area": "Площа",
    "Volume": "Об'єм",
    "Weight": "Вага",
    "Mass": "Маса",
    "Force": "Сила",
    "Energy": "Енергія",
    "Power": "Потужність",
    "Speed": "Швидкість",
    "Velocity": "Швидкість",
    "Acceleration": "Прискорення",
    "Direction": "Напрям",
    "Position": "Позиція",
    "Rotation": "Обертання",
    "Translation": "Переклад",
    "Matrix": "Матриця",
    "Vector": "Вектор",
    "Tensor": "Тензор",
    "Scalar": "Скаляр",
    "Array": "Масив",
    "List": "Список",
    "Dictionary": "Словник",
    "Map": "Карта",
    "Set": "Множина",
    "Tuple": "Кортеж",
    "String": "Рядок",
    "Integer": "Ціле число",
    "Float": "Дробове число",
    "Boolean": "Логічний",
    "Number": "Число",
    "Date": "Дата",
    "Time": "Час",
    "Duration": "Тривалість",
    "Period": "Період",
    "Frequency": "Частота",
    "Rate": "Швидкість",
    "Ratio": "Відношення",
    "Proportion": "Пропорція",
    "Percentage": "Відсоток",
    "Probability": "Ймовірність",
    "Random": "Випадковий",
    "Seed": "Сід",
    "Signal": "Сигнал",
    "Data": "Дані",
    "Metadata": "Метадані",
    "Header": "Заголовок",
    "Body": "Тіло",
    "Content": "Вміст",
    "Code": "Код",
    "Script": "Скрипт",
    "Program": "Програма",
    "Application": "Додаток",
    "System": "Система",
    "Network": "Мережа",
    "Server": "Сервер",
    "Client": "Клієнт",
    "Database": "База даних",
    "Query": "Запит",
    "Command": "Команда",
    "Action": "Дія",
    "Event": "Подія",
    "Message": "Повідомлення",
    "Notification": "Сповіщення",
    "Alert": "Сповіщення",
    "Exception": "Виняток",
    "Failure": "Невдача",
    "Success": "Успіх",
    "Complete": "Завершено",
    "Incomplete": "Незавершено",
    "Pending": "Очікує",
    "Processing": "Обробка",
    "Waiting": "Очікування",
    "Running": "Виконання",
    "Stopped": "Зупинено",
    "Paused": "Призупинено",
    "Resumed": "Відновлено",
    "Started": "Розпочато",
    "Finished": "Завершено",
    "Canceled": "Скасовано",
    "Failed": "Помилка",
    "Succeeded": "Успішно",
    "Aborted": "Перервано",
    "Terminated": "Завершено",
    "Killed": "Вбито",
    "Alive": "Живий",
    "Dead": "Мертвий",
    "Locked": "Заблоковано",
    "Unlocked": "Розблоковано",
    "Connected": "Підключено",
    "Disconnected": "Відключено",
    "Online": "Онлайн",
    "Offline": "Офлайн",
    "Available": "Доступний",
    "Unavailable": "Недоступний",
    "Busy": "Зайнятий",
    "Idle": "Пропускна здатність",
    "Loading": "Завантаження",
    "Saving": "Збереження",
    "Uploading": "Завантаження",
    "Downloading": "Завантаження",
    "Installing": "Встановлення",
    "Uninstalling": "Видалення",
    "Configuring": "Налаштування",
    "Building": "Збудова",
    "Compiling": "Компіляція",
    "Executing": "Виконання",
    "Handling": "Обробка",
    "Managing": "Керування",
    "Controlling": "Керування",
    "Monitoring": "Моніторинг",
    "Tracking": "Відстеження",
    "Logging": "Логування",
    "Recording": "Запис",
    "Capturing": "Захоплення",
    "Extracting": "Виділення",
    "Inserting": "Вставка",
    "Adding": "Додавання",
    "Removing": "Видалення",
    "Deleting": "Видалення",
    "Creating": "Створення",
    "Destroying": "Знищення",
    "Making": "Створення",
    "Building": "Збудова",
    "Constructing": "Створення",
    "Forming": "Формування",
    "Shaping": "Формування",
    "Sizing": "Розмір",
    "Scaling": "Масштаб",
    "Zooming": "Масштаб",
    "Panning": "Переміщення",
    "Scrolling": "Прокрутка",
    "Navigating": "Навігація",
    "Browsing": "Огляд",
    "Viewing": "Перегляд",
    "Displaying": "Відображення",
    "Rendering": "Рендеринг",
    "Drawing": "Малювання",
    "Painting": "Малювання",
    "Sketching": "Ескіз",
    "Designing": "Дизайн",
    "Styling": "Стилізація",
    "Theming": "Темізація",
    "Typing": "Введення",
    "Editing": "Редагування",
    "Copying": "Копіювання",
    "Pasting": "Вставка",
    "Cutting": "Вирізання",
    "Duplicating": "Дублювання",
    "Cloning": "Клонування",
    "Moving": "Рух",
    "Aligning": "Вирівнювання",
    "Centering": "Центрування",
    "Fitting": "Підлаштування",
    "Expanding": "Розгортання",
    "Collapsing": "Згортання",
    "Folding": "Складання",
    "Unfolding": "Розгортання",
    "Importing": "Імпорт",
    "Exporting": "Експорт",
    "Uploading": "Завантаження",
    "Downloading": "Завантаження",
    "Syncing": "Синхронізація",
    "Updating": "Оновлення",
    "Refreshing": "Оновлення",
    "Reloading": "Перезавантаження",
    "Restarting": "Перезапуск",
    "Rebooting": "Перезавантаження",
}

# Технічні терміни для полів вводу/виводу
TECHNICAL_TERMS = {
    'model': 'Модель',
    'noise': 'Шум',
    'sigmas': 'Сигми',
    'latent_image': 'Латентне зображення',
    'images': 'Зображення',
    'factor': 'Коефіцієнт',
    'strength': 'Сила',
    'steps': 'Кроки',
    'denoise': 'Денойз',
    'model_type': 'Тип моделі',
    'clip': 'CLIP',
    'vae': 'VAE',
    'seed': 'Сід',
    'control_net': 'ControlNet',
    'image': 'Зображення',
    'mask': 'Маска',
    'conditioning': 'Кондиціювання',
    'positive': 'Позитивне',
    'negative': 'Негативне',
    'width': 'Ширина',
    'height': 'Висота',
    'batch_size': 'Розмір партії',
    'samples': 'Семпли',
    'latent': 'Латент',
    'conditioning_strength': 'Сила кондиціювання',
    'min_cfg': 'Мін CFG',
    'cfg': 'CFG',
    'sampler_name': 'Назва семплера',
    'scheduler': 'Розклад',
    'guidance': 'Напрям',
    'refiner': 'Рефайнер',
    'upscale_ratio': 'Коефіцієнт масштабування',
    'residual': 'Залишок',
    'weight': 'Вага',
    'bias': 'Зміщення',
    'kernel_size': 'Розмір ядра',
    'stride': 'Крок',
    'padding': 'Відступ',
    'dilation': 'Дилатація',
    'groups': 'Групи',
    'channels': 'Канали',
    'features': 'Особливості',
    'units': 'Одиниці',
    'activation': 'Активація',
    'dropout': 'Дропаут',
    'learning_rate': 'Швидкість навчання',
    'epochs': 'Епохи',
    'batch': 'Партія',
    'shuffle': 'Перемішати',
    'validation': 'Валідація',
    'test': 'Тест',
    'train': 'Навчання',
    'evaluate': 'Оцінити',
    'predict': 'Передбачити',
    'generate': 'Генерувати',
    'transform': 'Трансформувати',
    'process': 'Обробити',
    'analyze': 'Аналізувати',
    'detect': 'Виявити',
    'segment': 'Сегментувати',
    'track': 'Відстежувати',
    'estimate': 'Оцінити',
    'measure': 'Виміряти',
    'calculate': 'Розрахувати',
    'compute': 'Обчислити',
    'render': 'Рендерити',
    'draw': 'Малювати',
    'paint': 'Малювати',
    'edit': 'Редагувати',
    'modify': 'Змінити',
    'adjust': 'Налаштувати',
    'optimize': 'Оптимізувати',
    'improve': 'Покращити',
    'enhance': 'Посилити',
    'reduce': 'Зменшити',
    'increase': 'Збільшити',
    'maintain': 'Підтримувати',
    'preserve': 'Зберегти',
    'restore': 'Відновити',
    'repair': 'Відремонтувати',
    'clean': 'Очистити',
    'filter': 'Фільтрувати',
    'sort': 'Сортувати',
    'organize': 'Організувати',
    'group': 'Групувати',
    'split': 'Розділити',
    'merge': 'Об\'єднати',
    'combine': 'Комбінувати',
    'separate': 'Відокремити',
    'isolate': 'Ізольований',
    'connect': 'Підключити',
    'disconnect': 'Відключити',
    'enable': 'Увімкнути',
    'disable': 'Вимкнути',
    'activate': 'Активувати',
    'deactivate': 'Деактивувати',
    'start': 'Почати',
    'stop': 'Зупинити',
    'pause': 'Пауза',
    'resume': 'Відновити',
    'restart': 'Перезапустити',
    'reset': 'Скинути',
    'clear': 'Очистити',
    'fill': 'Заповнити',
    'empty': 'Порожній',
    'add': 'Додати',
    'remove': 'Видалити',
    'insert': 'Вставити',
    'delete': 'Видалити',
    'replace': 'Замінити',
    'swap': 'Поміняти',
    'move': 'Рухати',
    'copy': 'Копіювати',
    'paste': 'Вставити',
    'cut': 'Вирізати',
    'duplicate': 'Дублювати',
    'clone': 'Клонувати',
    'rotate': 'Повернути',
    'scale': 'Масштаб',
    'flip': 'Відзеркалити',
    'mirror': 'Дзеркало',
    'skew': 'Скіс',
    'distort': 'Дисторція',
    'warp': 'Викривлення',
    'bend': 'Згинається',
    'twist': 'Крутити',
}

def translate_term(term, context=None):
    """Переклад одного терміну або фрази."""
    if not term or not isinstance(term, str):
        return term
    
    # Якщо термін в словнику - використовуємо його
    if term in TERM_TRANSLATIONS:
        return TERM_TRANSLATIONS[term]
    
    # Якщо це велике слово з великої літери - спробуємо перекласти кореневе слово
    if term[0].isupper() and ' ' not in term:
        lower_term = term.lower()
        if lower_term in TERM_TRANSLATIONS:
            translated = TERM_TRANSLATIONS[lower_term]
            return translated[0].upper() + translated[1:]
    
    # Якщо це шлях категорії (наприклад, "image/adjust/color")
    if '/' in term:
        parts = term.split('/')
        translated_parts = [translate_term(p) if p else p for p in parts]
        return '/'.join(translated_parts)
    
    # Якщо це параметр з advanced або іншими ключовими словами
    if term.startswith("advanced") or term == "advanced":
        return "розширені"
    
    # Переклад технічних термінів (input/output field names)
    if term in TECHNICAL_TERMS:
        return TECHNICAL_TERMS[term]
    
    # За замовчуванням - повертаємо оригінал
    return term

def find_empty_keys(data, prefix=''):
    """Знаходить усі порожні ключі в JSON структурі."""
    empty_keys = []
    for k, v in data.items():
        path = f'{prefix}.{k}' if prefix else k
        if isinstance(v, dict):
            # Рекурсивно обробляємо вкладені словники
            empty_keys.extend(find_empty_keys(v, path))
        elif not v or (isinstance(v, str) and v.strip() == ''):
            empty_keys.append(path)
    return empty_keys

def translate_value(key_path):
    """Перекладає значення на основі шляху ключа."""
    # Розбиваємо шлях на частини
    parts = key_path.split('.')
    
    # Беремо останню частину як назву поля
    field_name = parts[-1]
    
    # Перекладаємо поле
    return translate_term(field_name)

def fill_empty_translations(input_file, output_file):
    """Заповнює порожні переклади в main.json."""
    print(f"Завантаження {input_file}...")
    
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Знаходимо всі порожні ключі
    empty_keys = find_empty_keys(data)
    total_empty = len(empty_keys)
    
    print(f"Знайдено {total_empty} порожніх полів для перекладу...")
    
    # Заповнюємо порожні значення
    filled_count = 0
    for key_path in empty_keys:
        translated_value = translate_value(key_path)
        
        # Переходимо до відповідного місця в JSON структурі
        parts = key_path.split('.')
        current = data
        
        for i, part in enumerate(parts[:-1]):
            if part not in current:
                current[part] = {}
            current = current[part]
        
        # Встановлюємо перекладане значення
        field_name = parts[-1]
        current[field_name] = translated_value
        
        filled_count += 1
        
        # Виводимо прогрес кожні 50 полів
        if filled_count % 50 == 0:
            print(f"Заповнено {filled_count}/{total_empty} полів...")
    
    print(f"\nЗбереження перекладу до {output_file}...")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Готово! Заповнено {filled_count} порожніх полів.")

def main():
    """Головна функція."""
    # Шляхи до файлів
    base_dir = os.path.dirname(os.path.abspath(__file__))
    input_file = os.path.join(base_dir, "..", "locales", "uk", "main.json")
    output_file = os.path.join(base_dir, "..", "locales", "uk", "main_translated.json")
    
    # Заповнення порожніх перекладів
    fill_empty_translations(input_file, output_file)
    
    print(f"\nПереклад завершено!")
    print(f"Вихідний файл: {input_file}")
    print(f"Результат збережено в: {output_file}")

if __name__ == "__main__":
    main()
